// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acywnbgdmwnqdvlkgmsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjeXduYmdkbXducWR2bGtnbXNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNzAxNzQsImV4cCI6MjA2NDc0NjE3NH0.RSCG_ykniARnr3vyVhx5azBeb0SInFMBIpiq4bJin7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);